### Pandas

In [2]:
! pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\om sai compurer1\appdata\local\programs\python\python313\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\om sai compurer1\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.3.1)
Requirement already satisfied: scipy>=1.10.0 in c:\users\om sai compurer1\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in c:\users\om sai compurer1\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\om sai compurer1\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
! pip install pandas

Requirement already satisfied: pandas in c:\users\om sai compurer1\appdata\local\programs\python\python313\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\om sai compurer1\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\om sai compurer1\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\om sai compurer1\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\om sai compurer1\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd
import numpy as np
import sklearn as sns

In [5]:
df = pd.read_csv('Used_Bikes.csv')

In [6]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [7]:
df = pd.read_csv(r'C:\Users\om sai compurer1\Desktop\data science\ml\linear regression\Used_Bikes.csv')

In [8]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  str
 1   price       32648 non-null  float64
 2   city        32648 non-null  str
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  str
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  str
dtypes: float64(4), str(4)
memory usage: 2.0 MB

In [10]:
df.columns

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='str')

In [11]:
df.price

0         35000.0
1        119900.0
2        600000.0
3         65000.0
4         80000.0
           ...
32643     39000.0
32644     30000.0
32645     60000.0
32646     15600.0
32647     22000.0
Name: price, Length: 32648, dtype: float64

In [12]:
df.brand

0                  TVS
1        Royal Enfield
2              Triumph
3                  TVS
4               Yamaha
             ...
32643             Hero
32644              TVS
32645            Bajaj
32646             Hero
32647            Bajaj
Name: brand, Length: 32648, dtype: str

In [13]:
# check the record from the columns and also check the columns name
df[['brand','price']]

               brand     price
0                TVS   35000.0
1      Royal Enfield  119900.0
2            Triumph  600000.0
3                TVS   65000.0
4             Yamaha   80000.0
...              ...       ...
32643           Hero   39000.0
32644            TVS   30000.0
32645          Bajaj   60000.0
32646           Hero   15600.0
32647          Bajaj   22000.0

[32648 rows x 2 columns]

In [14]:
# check the record from the start of the data frame
df.head(10)

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
5,Yamaha FZs 150cc,53499.0,Delhi,25000.0,First Owner,6.0,150.0,Yamaha
6,Honda CB Hornet 160R ABS DLX,85000.0,Delhi,8200.0,First Owner,3.0,160.0,Honda
7,Hero Splendor Plus Self Alloy 100cc,45000.0,Delhi,12645.0,First Owner,3.0,100.0,Hero
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,Second Owner,7.0,500.0,Royal Enfield

In [15]:
# check the record from the end of the data frame
df.tail()

,bike_name,price,city,kms_driven,owner,age,power,brand
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [16]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
32643     True
32644     True
32645     True
32646     True
32647     True
Length: 32648, dtype: bool

In [17]:
df.duplicated().sum()

np.int64(25324)

In [18]:
df.drop_duplicates()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [19]:
# drop the duplicate record
df.drop_duplicates(inplace=True)

In [20]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
# is null
df.isnull()

      bike_name  price   city  kms_driven  owner    age  power  brand
0         False  False  False       False  False  False  False  False
1         False  False  False       False  False  False  False  False
2         False  False  False       False  False  False  False  False
3         False  False  False       False  False  False  False  False
4         False  False  False       False  False  False  False  False
...         ...    ...    ...         ...    ...    ...    ...    ...
9362      False  False  False       False  False  False  False  False
9369      False  False  False       False  False  False  False  False
9370      False  False  False       False  False  False  False  False
9371      False  False  False       False  False  False  False  False
9372      False  False  False       False  False  False  False  False

[7324 rows x 8 columns]

In [23]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [24]:
df.dropna()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

### check the unique values in the owner column

In [25]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [26]:
df['owner'].nunique()

4

In [27]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [28]:
df['brand'].nunique()

23

In [29]:
df['brand'].value_counts()

brand
Bajaj              2081
Royal Enfield      1346
Hero               1142
Honda               676
Yamaha              651
TVS                 481
KTM                 375
Suzuki              203
Harley-Davidson      91
Kawasaki             61
Hyosung              53
Mahindra             50
Benelli              46
Triumph              21
Ducati               20
BMW                  10
Jawa                  7
Indian                3
MV                    3
Rajdoot               1
LML                   1
Yezdi                 1
Ideal                 1
Name: count, dtype: int64

In [30]:
# df.drop(['brand','age'], axis=1 , inplace=True)

In [31]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

### Select data type

In [32]:
char =df.select_dtypes(include='object')

C:\Users\om sai compurer1\AppData\Local\Temp\ipykernel_3840\2101896211.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  char =df.select_dtypes(include='object')

In [33]:
char

,bike_name,city,owner,brand
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,First Owner,TVS
1,Royal Enfield Classic 350cc,Delhi,First Owner,Royal Enfield
2,Triumph Daytona 675R,Delhi,First Owner,Triumph
3,TVS Apache RTR 180cc,Bangalore,First Owner,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,First Owner,Yamaha
...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,Delhi,First Owner,Hero
9369,Bajaj Avenger 220cc,Bangalore,First Owner,Bajaj
9370,Harley-Davidson Street 750 ABS,Jodhpur,First Owner,Harley-Davidson
9371,Bajaj Dominar 400 ABS,Hyderabad,First Owner,Bajaj
9372,Bajaj Avenger Street 220,Hyderabad,First Owner,Bajaj

In [34]:
iint = df.select_dtypes(exclude='object')

In [35]:
iint

         price  kms_driven  age  power
0      35000.0     17654.0  3.0  110.0
1     119900.0     11000.0  4.0  350.0
2     600000.0       110.0  8.0  675.0
3      65000.0     16329.0  4.0  180.0
4      80000.0     10000.0  3.0  150.0
...        ...         ...  ...    ...
9362   25000.0     48587.0  8.0  150.0
9369   35000.0     60000.0  9.0  220.0
9370  450000.0      3430.0  4.0  750.0
9371  139000.0     21300.0  4.0  400.0
9372   80000.0      7127.0  5.0  220.0

[7324 rows x 4 columns]

In [36]:
charr =df.select_dtypes(include='O')

C:\Users\om sai compurer1\AppData\Local\Temp\ipykernel_3840\3500093658.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  charr =df.select_dtypes(include='O')

In [37]:
charr

,bike_name,city,owner,brand
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,First Owner,TVS
1,Royal Enfield Classic 350cc,Delhi,First Owner,Royal Enfield
2,Triumph Daytona 675R,Delhi,First Owner,Triumph
3,TVS Apache RTR 180cc,Bangalore,First Owner,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,First Owner,Yamaha
...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,Delhi,First Owner,Hero
9369,Bajaj Avenger 220cc,Bangalore,First Owner,Bajaj
9370,Harley-Davidson Street 750 ABS,Jodhpur,First Owner,Harley-Davidson
9371,Bajaj Dominar 400 ABS,Hyderabad,First Owner,Bajaj
9372,Bajaj Avenger Street 220,Hyderabad,First Owner,Bajaj

In [38]:
df[df['owner']=='First Owner']

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [39]:
df[df['price']>100000]

,bike_name,price,city,kms_driven,owner,age,power,brand
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
16,Bajaj Pulsar RS200 ABS,120000.0,Bangalore,23000.0,First Owner,3.0,200.0,Bajaj
18,Benelli 302R 300CC,240000.0,Mumbai,15025.0,Second Owner,3.0,302.0,Benelli
...,...,...,...,...,...,...,...,...
9337,Royal Enfield Himalayan 410cc,120000.0,Gurgaon,8492.0,First Owner,5.0,410.0,Royal Enfield
9338,Royal Enfield Himalayan 410cc,138000.0,Delhi,5000.0,First Owner,5.0,410.0,Royal Enfield
9348,KTM Duke 390cc,195000.0,Mumbai,4568.0,First Owner,4.0,390.0,KTM
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj

In [40]:
cityy =df[df['city']=='Delhi']

In [41]:
cityy

,bike_name,price,city,kms_driven,owner,age,power,brand
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
5,Yamaha FZs 150cc,53499.0,Delhi,25000.0,First Owner,6.0,150.0,Yamaha
6,Honda CB Hornet 160R ABS DLX,85000.0,Delhi,8200.0,First Owner,3.0,160.0,Honda
7,Hero Splendor Plus Self Alloy 100cc,45000.0,Delhi,12645.0,First Owner,3.0,100.0,Hero
...,...,...,...,...,...,...,...,...
9336,Yamaha YZF-R3 320cc,220000.0,Delhi,7130.0,First Owner,5.0,320.0,Yamaha
9338,Royal Enfield Himalayan 410cc,138000.0,Delhi,5000.0,First Owner,5.0,410.0,Royal Enfield
9340,Honda CB Trigger 150cc,34400.0,Delhi,24513.0,Second Owner,8.0,150.0,Honda
9344,Royal Enfield Bullet Twinspark 350cc,80000.0,Delhi,56968.0,First Owner,8.0,350.0,Royal Enfield
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero

In [42]:
cityy[cityy['price']<10000]

,bike_name,price,city,kms_driven,owner,age,power,brand
3121,TVS Star City 110cc,9000.0,Delhi,72302.0,First Owner,15.0,110.0,TVS
4656,Bajaj Discover 125cc,8000.0,Delhi,21493.0,First Owner,16.0,125.0,Bajaj
4726,Bajaj CT 100 100cc,9000.0,Delhi,50000.0,First Owner,16.0,100.0,Bajaj
4922,Bajaj Pulsar 150cc,6400.0,Delhi,100000.0,First Owner,18.0,150.0,Bajaj
4923,Bajaj Pulsar 150cc,6700.0,Delhi,81000.0,First Owner,17.0,150.0,Bajaj
4927,Hero CBZ Xtreme 150cc,9000.0,Delhi,62135.0,Second Owner,13.0,150.0,Hero
6701,Bajaj Pulsar 150cc,9500.0,Delhi,50000.0,First Owner,16.0,150.0,Bajaj
9194,Hero Ambition 135cc,5000.0,Delhi,82178.0,First Owner,18.0,135.0,Hero

In [43]:
df[(df['owner']=='First Owner') & (df['kms_driven']>50000) & (df['brand']=='Hero') & (df['age']>2)]

,bike_name,price,city,kms_driven,owner,age,power,brand
120,Hero Splendor Plus 100cc,19695.0,Ernakulam,51576.0,First Owner,6.0,100.0,Hero
187,Hero Karizma R 223cc,36000.0,Bangalore,54560.0,First Owner,8.0,223.0,Hero
1262,Hero Splendor Plus 100cc,15000.0,Mumbai,60000.0,First Owner,15.0,100.0,Hero
1314,Hero Passion Pro 100cc,22000.0,Pune,97401.0,First Owner,9.0,100.0,Hero
1516,Hero Splendor Plus 100cc,9500.0,Ghaziabad,60000.0,First Owner,17.0,100.0,Hero
...,...,...,...,...,...,...,...,...
9099,Hero Passion Pro 100cc,26000.0,Chennai,81414.0,First Owner,7.0,100.0,Hero
9140,Hero Passion Plus 100cc,20000.0,Chennai,78394.0,First Owner,10.0,100.0,Hero
9194,Hero Ambition 135cc,5000.0,Delhi,82178.0,First Owner,18.0,135.0,Hero
9212,Hero CBZ Xtreme 150cc,22000.0,Delhi,55000.0,First Owner,14.0,150.0,Hero
9343,Hero Passion Plus 100cc,24000.0,Hyderabad,68000.0,First Owner,14.0,100.0,Hero

In [44]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [45]:
brand_dict ={
                'TVS': 1,   'Royal Enfield': 2,         'Triumph': 3,          'Yamaha': 4,
           'Honda': 5,            'Hero': 6,           'Bajaj': 7,          'Suzuki': 8,
         'Benelli': 9,             'KTM': 10,        'Mahindra': 11,        'Kawasaki': 12,
          'Ducati': 13,         'Hyosung': 14, 'Harley-Davidson': 15,            'Jawa': 16,
             'BMW': 17,          'Indian': 18,         'Rajdoot': 19,             'LML': 20,
           'Yezdi': 21,              'MV': 22,           'Ideal': 23
}

In [46]:
df['brand']=df['brand'].map(brand_dict)

In [47]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,1
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,2
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,3
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,1
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,4
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,6
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,7
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,15
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,7
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,7

In [48]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   str
 1   price       7324 non-null   float64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   str
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   int64
dtypes: float64(4), int64(1), str(3)
memory usage: 515.0 KB

In [49]:
df['brand_encoding']=df['brand'].map(brand_dict)

In [50]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand,brand_encoding
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,1,NaN
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,2,NaN
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,3,NaN
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,1,NaN
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,4,NaN
...,...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,6,NaN
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,7,NaN
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,15,NaN
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,7,NaN
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,7,NaN

In [51]:
df.drop('brand_encoding', axis=1, inplace=True)

In [52]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,1
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,2
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,3
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,1
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,4
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,6
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,7
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,15
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,7
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,7

In [53]:
df.duplicated().sum()

np.int64(0)

In [54]:
x = df.drop('price', axis=1)

In [55]:
y = df['price']

In [56]:
y

0        35000.0
1       119900.0
2       600000.0
3        65000.0
4        80000.0
          ...
9362     25000.0
9369     35000.0
9370    450000.0
9371    139000.0
9372     80000.0
Name: price, Length: 7324, dtype: float64

In [57]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [58]:
owmer_dict ={
    'First Owner': 1,
    'Second Owner': 2,
    'Third Owner': 3,
    'Fourth Owner Or More': 4
}

In [59]:
df['owner']=df['owner'].map(owmer_dict)

In [60]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,1,3.0,110.0,1
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1,4.0,350.0,2
2,Triumph Daytona 675R,600000.0,Delhi,110.0,1,8.0,675.0,3
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,1,4.0,180.0,1
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,1,3.0,150.0,4
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,1,8.0,150.0,6
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,1,9.0,220.0,7
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,1,4.0,750.0,15
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,1,4.0,400.0,7
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,1,5.0,220.0,7

In [61]:
df['city'].unique()

<StringArray>
[   'Ahmedabad',        'Delhi',    'Bangalore',       'Mumbai',
       'Kalyan',    'Faridabad',       'Mettur',    'Hyderabad',
      'Kaithal',      'Gurgaon',
 ...
  'Bhubaneswar',      'Raiganj', 'Bhilai Nagar',       'Baloda',
     'Anantnag',   'Berhampore',      'Silvasa',       'Hospet',
        'Palai',        'Sidhi']
Length: 443, dtype: str

In [62]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,1,3.0,110.0,1
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1,4.0,350.0,2
2,Triumph Daytona 675R,600000.0,Delhi,110.0,1,8.0,675.0,3
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,1,4.0,180.0,1
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,1,3.0,150.0,4
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,1,8.0,150.0,6
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,1,9.0,220.0,7
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,1,4.0,750.0,15
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,1,4.0,400.0,7
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,1,5.0,220.0,7

In [63]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   str
 1   price       7324 non-null   float64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   int64
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   int64
dtypes: float64(4), int64(2), str(2)
memory usage: 515.0 KB

In [64]:
y = df['price']

In [65]:
x = df.drop('price', axis=1)

In [66]:
y

0        35000.0
1       119900.0
2       600000.0
3        65000.0
4        80000.0
          ...
9362     25000.0
9369     35000.0
9370    450000.0
9371    139000.0
9372     80000.0
Name: price, Length: 7324, dtype: float64

In [67]:
y.duplicated().sum()

np.int64(6092)

In [68]:
y.drop_duplicates(inplace=True)

In [69]:
y

0        35000.0
1       119900.0
2       600000.0
3        65000.0
4        80000.0
          ...
9282    139100.0
9284    115800.0
9312     65450.0
9339     11400.0
9346     61483.0
Name: price, Length: 1232, dtype: float64

In [70]:
y.duplicated().sum()

np.int64(0)

In [71]:
y.unique()

array([ 35000., 119900., 600000., ...,  65450.,  11400.,  61483.],
      shape=(1232,))

In [72]:
x

,bike_name,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,17654.0,1,3.0,110.0,1
1,Royal Enfield Classic 350cc,Delhi,11000.0,1,4.0,350.0,2
2,Triumph Daytona 675R,Delhi,110.0,1,8.0,675.0,3
3,TVS Apache RTR 180cc,Bangalore,16329.0,1,4.0,180.0,1
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,10000.0,1,3.0,150.0,4
...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,Delhi,48587.0,1,8.0,150.0,6
9369,Bajaj Avenger 220cc,Bangalore,60000.0,1,9.0,220.0,7
9370,Harley-Davidson Street 750 ABS,Jodhpur,3430.0,1,4.0,750.0,15
9371,Bajaj Dominar 400 ABS,Hyderabad,21300.0,1,4.0,400.0,7
9372,Bajaj Avenger Street 220,Hyderabad,7127.0,1,5.0,220.0,7

In [73]:
print(x.shape)

(7324, 7)

In [74]:
print(y.shape)

(1232,)

In [75]:
df = df.dropna()
x = df.drop('price', axis=1)
y = df['price']

In [76]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [77]:
print(x_train.shape , x_test.shape , y_train.shape , y_test.shape)

(5859, 7) (1465, 7) (5859,) (1465,)

In [78]:
x_train

,bike_name,city,kms_driven,owner,age,power,brand
5789,TVS Victor GX 110cc,Mumbai,68857.0,1,15.0,110.0,1
3451,Royal Enfield Thunderbird 500cc,Pune,5740.0,1,6.0,500.0,2
735,Hero Passion Xpro 110cc,Hoshiarpur,28329.0,1,6.0,110.0,6
7533,Yamaha FZ S V 2.0 150cc,Bangalore,42966.0,1,7.0,150.0,4
8461,Royal Enfield Classic Squadron Blue 500cc,Jaipur,8000.0,1,5.0,500.0,2
...,...,...,...,...,...,...,...
6522,Bajaj Pulsar NS200,Kolkata,56000.0,1,9.0,200.0,7
6583,Royal Enfield Thunderbird 500cc,Hyderabad,22493.0,1,5.0,500.0,2
6856,Bajaj Avenger Street 150,Faridabad,17477.0,1,5.0,150.0,7
1028,Yamaha FZ16 150cc,Mumbai,14836.0,1,8.0,150.0,4
9250,Honda CBR 250R,Delhi,8000.0,1,10.0,250.0,5

In [79]:
x_train['bike_name'].inplace =True

In [80]:
x_train.drop(['city','bike_name'], axis=1 , inplace=True)

In [81]:
y_train

5789     18000.0
3451    140000.0
735      32000.0
7533     40000.0
8461    160000.0
          ...
6522     48928.0
6583    114000.0
6856     41000.0
1028     40000.0
9250     80000.0
Name: price, Length: 5859, dtype: float64

In [82]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [83]:
lr.fit(x_train, y_train)

LinearRegression()

In [84]:
x_test.drop(['city','bike_name'], axis=1 , inplace=True)

In [85]:
x_test

      kms_driven  owner   age  power  brand
4909     22500.0      1   6.0  350.0      2
1942      3198.0      1   5.0  500.0      2
5763     15000.0      1   6.0  220.0      7
4800     27000.0      1  12.0  150.0      4
7614     16764.0      1   9.0  100.0      6
...          ...    ...   ...    ...    ...
5653     16523.0      1   5.0  750.0     15
609       2881.0      1   7.0  250.0     14
4211     23833.0      1   4.0  150.0      8
6379      9282.0      1   7.0  500.0      2
647       2980.0      1   6.0  160.0      1

[1465 rows x 5 columns]

In [86]:
lr.predict(x_test)

array([125382.54523531, 216422.20333617,  96966.48595241, ...,
        72233.83615101, 208856.67620686,   9305.60087569], shape=(1465,))

In [87]:
honda_bike = lr.predict([[22500.0,	1,	6.0,	350.0,	2]])

c:\Users\om sai compurer1\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [88]:
honda_bike

array([125382.54523531])

In [89]:
from sklearn.svm import SVR
sv = SVR()

In [90]:
sv.fit(x_train, y_train)

SVR()

In [92]:
sv.score(x_test, y_test)

-0.058810958372743416

In [94]:
pred =sv.predict(x_test)
pred

array([54600.4698477 , 55129.47131119, 54861.78539028, ...,
       54550.9225554 , 55020.38248866, 55131.93435183], shape=(1465,))

In [95]:
pred[0:20]

array([54600.4698477 , 55129.47131119, 54861.78539028, 54433.67728621,
       54804.26431787, 55109.94158252, 53983.67981309, 55153.44041585,
       54829.56379125, 54856.99083596, 54858.90615198, 54032.070002  ,
       54810.38070957, 54655.41677884, 53926.37854842, 54581.99517125,
       54861.77116343, 54922.10527375, 54555.83397107, 54405.37203315])

In [96]:
y_test[0:20]

4909     88400.0
1942    102850.0
5763     67000.0
4800     30000.0
7614     20000.0
5129    141000.0
8349     35000.0
1874    140000.0
2427     32500.0
5567     85000.0
2653     45000.0
8942     20000.0
5887     36000.0
5199     32000.0
1860     43000.0
8417    115000.0
2219    120000.0
4017     17000.0
7838     38000.0
137      48000.0
Name: price, dtype: float64

In [91]:
import imblearn
from imblearn.over_sampling import SMOTE